/*CREATE DATABASE IF NOT EXISTS team-v;
USE team-v;
*/
DROP TABLE IF EXISTS meetings;

CREATE TABLE meetings (
	id SERIAL,
	meeting INT NOT NULL,
	time_started TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	time_finished TIMESTAMP,
	PRIMARY KEY (id));
